import OpenAI from "openai";
import { splitIntoChunks } from "./textExtractor";
import type { AiHighlightedSection } from "@shared/schema";

const openai = new OpenAI({
  apiKey: process.env.AI_INTEGRATIONS_OPENAI_API_KEY,
  baseURL: process.env.AI_INTEGRATIONS_OPENAI_BASE_URL,
});

export interface AiScanResult {
  aiScore: number;
  verdict: "human" | "likely_human" | "mixed" | "likely_ai" | "ai";
  analysis: string;
  highlightedSections: AiHighlightedSection[];
}

function getVerdict(score: number): "human" | "likely_human" | "mixed" | "likely_ai" | "ai" {
  if (score < 20) return "human";
  if (score < 40) return "likely_human";
  if (score < 60) return "mixed";
  if (score < 80) return "likely_ai";
  return "ai";
}

export async function scanForAI(text: string): Promise<AiScanResult> {
  const chunks = splitIntoChunks(text, 500);
  const results: { text: string; score: number; reason: string; startIndex: number; endIndex: number }[] = [];
  let totalScore = 0;
  let currentIndex = 0;
  const analysisPoints: string[] = [];

  for (const chunk of chunks.slice(0, 8)) {
    try {
      const response = await openai.chat.completions.create({
        model: "gpt-4o",
        messages: [
          {
            role: "system",
            content: `You are an expert AI content detector with deep knowledge of how AI language models generate text. Analyze the following text carefully and estimate the probability (0-100) that it was generated by an AI like ChatGPT, Claude, or similar models.

DETECTION CRITERIA - Look for these AI-generated content indicators:
1. STRUCTURAL PATTERNS:
   - Unnaturally perfect grammar and punctuation
   - Consistent paragraph lengths
   - Formulaic transitions ("Furthermore," "Moreover," "In conclusion")
   - Lists and bullet points in prose
   
2. LINGUISTIC MARKERS:
   - Hedging language ("It's important to note," "It should be mentioned")
   - Overly balanced arguments without strong opinions
   - Generic, non-specific examples
   - Repetitive sentence structures
   
3. CONTENT CHARACTERISTICS:
   - Lack of personal anecdotes or unique experiences
   - Absence of typos, colloquialisms, or informal language
   - Encyclopedic tone rather than conversational
   - Excessive use of transitional phrases

4. SEMANTIC PATTERNS:
   - Broad coverage without deep expertise
   - Predictable topic progression
   - Lack of controversial or bold claims
   - Generic conclusions that summarize rather than conclude with new insights

SCORING GUIDELINES:
- 0-20: Clearly human-written (personal voice, unique style, natural imperfections)
- 21-40: Likely human-written (minor AI-like patterns, possibly edited)
- 41-60: Uncertain (mixed signals, could be AI-assisted)
- 61-80: Likely AI-generated (multiple AI markers present)
- 81-100: Clearly AI-generated (strong AI patterns throughout)

Be accurate and avoid false positives. Academic or formal writing isn't automatically AI-generated.

Respond with ONLY a valid JSON object: {"score": number, "reason": "specific explanation citing observed patterns"}`
          },
          {
            role: "user",
            content: chunk
          }
        ],
        max_completion_tokens: 300,
      });

      const content = response.choices[0]?.message?.content || '{"score": 0, "reason": "Analysis failed"}';
      const cleanedContent = content.replace(/```json\n?|\n?```/g, "").trim();
      const parsed = JSON.parse(cleanedContent);
      const score = Math.min(100, Math.max(0, parsed.score || 0));
      const reason = parsed.reason || "No specific patterns detected";

      const startIndex = text.indexOf(chunk);
      results.push({
        text: chunk,
        score,
        reason,
        startIndex: startIndex >= 0 ? startIndex : currentIndex,
        endIndex: (startIndex >= 0 ? startIndex : currentIndex) + chunk.length,
      });
      totalScore += score;
      
      if (score > 35) {
        analysisPoints.push(reason);
      }
    } catch (error) {
      console.error("AI detection error for chunk:", error);
    }
    currentIndex += chunk.length + 1;
  }

  const avgScore = results.length > 0 ? totalScore / results.length : 0;
  const verdict = getVerdict(avgScore);

  const highlightedSections: AiHighlightedSection[] = results
    .filter(r => r.score > 35)
    .map(r => ({
      text: r.text,
      startIndex: r.startIndex,
      endIndex: r.endIndex,
      aiProbability: r.score,
      reason: r.reason,
    }));

  let analysis = "";
  if (avgScore < 20) {
    analysis = "This content appears to be written by a human. The writing shows natural patterns, personal voice, and authentic expression.";
  } else if (avgScore < 40) {
    analysis = "This content is likely human-written but may have minor AI-like patterns. It could be well-edited or follow formal writing conventions.";
  } else if (avgScore < 60) {
    analysis = "This content shows mixed signals. It could be AI-assisted writing or heavily edited AI-generated content. Key observations: " + analysisPoints.slice(0, 3).join("; ");
  } else if (avgScore < 80) {
    analysis = "This content is likely AI-generated. Multiple AI patterns were detected including: " + analysisPoints.slice(0, 3).join("; ");
  } else {
    analysis = "This content strongly appears to be AI-generated. Strong indicators include: " + analysisPoints.slice(0, 3).join("; ");
  }

  return {
    aiScore: avgScore,
    verdict,
    analysis,
    highlightedSections,
  };
}
